spring.application.name=user-management

spring.datasource.url=jdbc:postgresql://localhost:5432/userdb
spring.datasource.username=postgres
spring.datasource.password=Gouthamnanda999

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true